from character import Character
from skin import Skin

CHARACTER_SKINS = {
    "Sonic": [
        ("Default", "Rare", "images/sonic_default.png"),
        ("Adventure", "Rare", "images/sonic_adventure.png"),
        ("Gold Racesuit", "Legendary", "images/sonic_goldracesuit_legendary.png"),
        ("Gold Racesuit", "Limited", "images/sonic_goldracesuit_limited.png"),
        ("Riders", "Epic", "images/sonic_riders.png"),
        ("Stealth", "Epic", "images/sonic_stealth.png"),
        ("Birthday", "Legendary", "images/sonic_birthday.png"),
        ("Frontiers", "Legendary", "images/sonic_frontiers.png"),
        ("New Yoke", "Legendary", "images/sonic_newyoke.png"),
        ("Gold Style", "Legendary", "images/sonic_goldstyle.png"),
        ("Zebra", "Legendary", "images/sonic_zebra.png"),
        ("No Place", "Legendary", "images/sonic_noplace.png"),
        ("Steampunk", "Legendary", "images/sonic_steampunk.png"),
        ("Extreme Rider", "Legendary", "images/sonic_extremerider.png"),
        ("Gold Racesuit", "Exotic", "images/sonic_goldracesuit_exotic.png"),
        ("Jester", "Legendary", "images/sonic_jester.png"),
        ("Karate", "Legendary", "images/sonic_karate.png"),
        ("Neon", "Legendary", "images/sonic_neon.png"),
        ("Ninja", "Legendary", "images/sonic_ninja.png"),
        ("Pirate", "Legendary", "images/sonic_pirate.png"),
        ("Rockstar", "Legendary", "images/sonic_rockstar.png"),
        ("Sailor", "Uncommon", "images/sonic_sailor.png"),
        ("Grind Shoe", "Exotic", "images/sonic_grindshoe_exotic.png"),
        ("Racesuit", "Exotic", "images/sonic_racesuit_exotic.png"),
        ("Tuxedo", "Exotic", "images/sonic_tuxedo_exotic.png"),
        ("Party", "Exotic", "images/sonic_party_exotic.png"),
        ("Ninja Maskless", "Exotic", "images/sonic_ninjamaskless_exotic.png"),
        ("Chrome Style", "Exotic", "images/sonic_chromestyle_exotic.png"),
        ("Luminosity", "Exotic", "images/sonic_luminosity_exotic.png"),
        ("Summer", "Seasonal", "images/sonic_summer.png"),
        ("Vampire", "Seasonal", "images/sonic_vampire.png"),
        ("Holiday Cheer", "Seasonal", "images/sonic_holiday.png"),
        ("Winter", "Seasonal", "images/sonic_winter.png"),
        ("Valentines", "Seasonal", "images/sonic_valentine.png"),
        ("Easter", "Seasonal", "images/sonic_easter.png"),
        ("Chrome Style", "Limited", "images/sonic_chromestyle_limited.png"),
        ("Phantom Rider Unmasked", "Limited", "images/sonic_phantomriderunmasked_limited.png"),
        ("Luminosity", "Limited", "images/sonic_luminosity_limited.png"),
        ("Phantom Rider Unmasked", "Exotic", "images/sonic_phantomriderunmasked_exotic.png"),
        ("Fake Metal", "Exotic", "images/sonic_fakemetal_exotic.png"),
        ("Fake Gold", "Limited", "images/sonic_fakegold_limited.png"),
        ("Fake Gold", "Exotic", "images/sonic_fakegold_exotic.png"),
        ("Werehog", "Seasonal", "images/sonic_werehog.png"),
        ("Werehog (Chained)", "Seasonal", "images/sonic_chainedwerehog.png"),
        ("Movie", "Exotic", "images/sonic_movie.png"),
        ("LEGO", "Legendary", "images/sonic_lego.png")
        # ("", "", "images/sonic_"),
    ],
    "Tails": [
        ("Default", "Rare", "images/tails_default.png"),
        ("Party Hat", "Rare", "images/tails_partyhat.png"),
        ("Sailor", "Epic", "images/tails_sailor_epic.png"),
        ("Mechanic", "Epic", "images/tails_mechanic_epic.png"),
        ("Aviator", "Epic", "images/tails_aviator_epic.png"),
        ("Riders", "Epic", "images/tails_riders_epic.png"),
        ("Detective", "Legendary", "images/tails_detective_legendary.png"),
        ("Racesuit", "Legendary", "images/tails_racesuit_legendary.png"),
        ("Toy Maker", "Legendary", "images/tails_toymaker_legendary.png"),
        ("Adventure", "Legendary", "images/tails_adventure_legendary.png"),
        ("Extreme Rider", "Legendary", "images/tails_extremerider_legendary.png"),
        ("Gold Style", "Exotic", "images/tails_goldstyle_exotic.png"),
        ("Elf", "Seasonal", "images/tails_elf.png"),
        ("Summer", "Seasonal", "images/tails_summer.png"),
        ("Gold Style", "Limited", "images/tails_goldstyle_limited.png"),
        ("Luminosity", "Limited", "images/tails_luminosity_limited.png"),
        ("Fake Metal", "Legendary", "images/tails_fakemetal_legendary.png"),
        ("Nine", "Legendary", "images/tails_nine.png"),
        ("Movie", "Legendary", "images/tails_movie.png"),
        ("LEGO", "Epic", "images/tails_lego.png")
        # ("", "", "images/tails_"),
    ],
    "Knuckles": [
        ("Default", "Rare", "images/knuckles_default.png"),
        ("Party Hat", "Rare", "images/knuckles_partyhat_rare.png"),
        ("Treasure Hunter", "Epic", "images/knuckles_treasurehunter_epic.png"),
        ("Riders", "Epic", "images/knuckles_riders_epic.png"),
        ("Camper", "Epic", "images/knuckles_camper_epic.png"),
        ("Diesel Punk", "Epic", "images/knuckles_diesel_epic.png"),
        ("Adventure", "Legendary", "images/knuckles_adventure_legendary.png"),
        ("Racesuit", "Exotic", "images/knuckles_racesuit_exotic.png"),
        ("DJ", "Exotic", "images/knuckles_dj_exotic.png"),
        ("Gold Style", "Exotic", "images/knuckles_goldstyle_exotic.png"),
        ("Tuxedo", "Exotic", "images/knuckles_tuxedo_exotic.png"),
        ("Skeleton", "Seasonal", "images/knuckles_skeleton.png"),
        ("Reindeer", "Seasonal", "images/knuckles_reindeer.png"),
        ("Summer", "Seasonal", "images/knuckles_summer.png"),
        ("Gold Style", "Limited", "images/knuckles_goldstyle_limited.png"),
        ("Chrome Style", "Limited", "images/knuckles_chromestyle_limited.png"),
        ("Luminosity", "Limited", "images/knuckles_luminosity_limited.png"),
        ("Fake Metal", "Legendary", "images/knuckles_fakemetal_legendary.png"),
        ("Fake Gold", "Limited", "images/knuckles_fakegold_limited.png"),
        ("Fake Gold", "Exotic", "images/knuckles_fakegold_exotic.png"),
        ("Renegade", "Legendary", "images/knuckles_renegade.png"),
        ("Dread", "Exotic", "images/knuckles_dread.png"),
        ("Movie", "Legendary", "images/knuckles_movie.png"),
        ("Series", "Exotic", "images/knuckles_series.png"),
        ("LEGO", "Epic", "images/knuckles_lego.png"),
        ("Luminosity", "Exotic", "images/knuckles_luminosity_exotic.png")
        # ("", "", "images/knuckles_"),
    ],
    "Amy": [
        ("Default", "Rare", "images/amy_default.png"),
        ("Party Hat", "Legendary", "images/amy_partyhat_legendary.png"),
        ("Riders", "Epic", "images/amy_riders_epic.png"),
        ("Kunoichi", "Epic", "images/amy_kunoichi_epic.png"),
        ("Popstar", "Epic", "images/amy_popstar_epic.png"),
        ("Racesuit", "Legendary", "images/amy_racesuit_legendary.png"),
        ("Extreme Rider", "Legendary", "images/amy_extremerider_legendary.png"),
        ("Fortune Teller", "exotic", "images/amy_fortuneteller.png"),
        ("Summer", "Seasonal", "images/amy_summer.png"),
        ("Gothic", "Seasonal", "images/amy_gothic.png"),
        ("Valentines", "Seasonal", "images/amy_valentine.png"),
        ("Easter", "Seasonal", "images/amy_easter.png"),
        ("Holiday Cheer", "Seasonal", "images/amy_holiday.png"),
        ("Luminosity", "Limited", "images/amy_luminosity_limited.png"),
        ("Luminosity", "Exotic", "images/amy_luminosity_exotic.png"),
        ("Rusty Rose", "Legendary", "images/amy_rustyrose.png"),
        ("Black Rose", "Legendary", "images/amy_blackrose.png"),
        ("LEGO", "Epic", "images/amy_lego.png")
        # ("", "", "images/amy_"),
    ],
    "Big": [
        ("Default", "Epic", "images/big_default.png"),
        ("Angler", "Legendary", "images/big_angler_legendary.png"),
        ("Racesuit", "Exotic", "images/big_racesuit_exotic.png"),
        ("Holiday", "Seasonal", "images/big_holiday.png"),
        # ("", "", "images/big_"),
    ],
    "Cream": [
        ("Default", "Epic", "images/cream_default.png"),
        ("Riders", "Legendary", "images/cream_riders_legendary.png"),
        ("Racesuit", "Exotic", "images/cream_racesuit_exotic.png"),
        ("Witch", "Seasonal", "images/cream_witch.png"),
        ("Winter", "Seasonal", "images/cream_winter.png"),
        ("Easter", "Seasonal", "images/cream_easter.png"),
        ("Summer", "Seasonal", "images/cream_summer.png"),
        # ("", "", "images/cream_"),
    ],
    "Shadow": [
        ("Default", "Legendary", "images/shadow_default.png"),
        ("Flame", "Legendary", "images/shadow_flame.png"),
        ("Riders", "Legendary", "images/shadow_riders_legendary.png"),
        ("Gold Style", "Legendary", "images/shadow_goldstyle_legendary.png"),
        ("Racesuit", "Legendary", "images/shadow_racesuit_legendary.png"),
        ("Royal King", "Legendary", "images/shadow_royalking_legendary.png"),
        ("Gold Racesuit", "Legendary", "images/shadow_goldracesuit_legendary.png"),
        ("Adventure", "Legendary", "images/shadow_adventure_legendary.png"),
        ("Ninja", "Legendary", "images/shadow_ninja_legendary.png"),
        ("Biker", "Legendary", "images/shadow_biker_legendary.png"),
        ("Darkness Riders", "Legendary", "images/shadow_darknessriders_legendary.png"),
        ("Karate", "Legendary", "images/shadow_karate_legendary.png"),
        ("Captain", "Legendary", "images/shadow_captain_legendary.png"),
        ("Extreme Rider", "Legendary", "images/shadow_extremerider_legendary.png"),
        ("Cheetah", "Exotic", "images/shadow_cheetah_exotic.png"),
        ("Clockwork", "Exotic", "images/shadow_clockwork_exotic.png"),
        ("Rockstar", "Exotic", "images/shadow_rockstar_exotic.png"),
        ("Warlock", "Exotic", "images/shadow_warlock_exotic.png"),
        ("Ninja Maskless", "Exotic", "images/shadow_ninjamaskless_exotic.png"),
        ("Luminosity", "Exotic", "images/shadow_luminosity_exotic.png"),
        ("Neon", "Exotic", "images/shadow_neon_exotic.png"),
        ("Vampire", "Seasonal", "images/shadow_vampire.png"),
        ("Winter", "Seasonal", "images/shadow_winter.png"),
        ("Summer", "Seasonal", "images/shadow_summer.png"),
        ("Holiday", "Seasonal", "images/shadow_holiday.png"),
        ("Luminosity", "Limited", "images/shadow_luminosity_limited.png"),
        ("Chrome Style", "Limited", "images/shadow_chromestyle_limited.png"),
        ("Gold Racesuit", "Limited", "images/shadow_goldracesuit_limited.png"),
        ("Android (Orange)", "Legendary", "images/shadow_androidorange.png"),
        ("Android (Green)", "Legendary", "images/shadow_androidgreen.png"),
        ("Android (Blue)", "Epic", "images/shadow_androidblue.png"),
        ("Android (Pink)", "Epic", "images/shadow_androidpink.png"),
        ("Android (Red)", "Legendary", "images/shadow_androidred.png"),
        ("Android (Yellow)", "Legendary", "images/shadow_androidyellow.png"),
        ("Android (Gold)", "Exotic", "images/shadow_androidgold_exotic.png"),
        ("Android (Gold)", "Limited", "images/shadow_androidgold_limited.png"),
        ("LEGO", "Epic", "images/shadow_lego.png"),
        # ("", "", "images/shadow_"),
    ],
    "Rouge": [
        ("Default", "Legendary", "images/rouge_default.png"),
        ("Riders", "Legendary", "images/rouge_riders_legendary.png"),
        ("Prime", "Legendary", "images/rouge_prime_legendary.png"),
        ("Adventure", "Legendary", "images/rouge_adventure_legendary.png"),
        ("Racesuit", "Exotic", "images/rouge_racesuit_exotic.png"),
        ("Gold Style", "Exotic", "images/rouge_goldstyle_exotic.png"),
        ("Kunoichi", "Exotic", "images/rouge_kunoichi_exotic.png"),
        ("Rockstar", "Exotic", "images/rouge_rockstar_exotic.png"),
        ("Witch", "Seasonal", "images/rouge_witch.png"),
        ("Summer", "Seasonal", "images/rouge_summer.png"),
        ("Gold Style", "Limited", "images/rouge_goldstyle_limited.png"),
        ("Luminosity", "Limited", "images/rouge_luminosity_limited.png"),
        ("Chrome Style", "Limited", "images/rouge_chromestyle_limited.png"),
        ("Luminosity", "Exotic", "images/rouge_luminosity_exotic.png"),
        ("Rebel", "Legendary", "images/rouge_rebel.png"),
        ("Batten", "Legendary", "images/rouge_batten.png"),
        # ("", "", "images/rouge_"),
    ],
    "Omega": [
        ("Default", "Legendary", "images/omega_default.png"),
        ("Gold Style", "Legendary", "images/omega_goldstyle_legendary.png"),
        ("Racesuit", "Exotic", "images/omega_racesuit_exotic.png"),
        ("Pumpkin", "Seasonal", "images/omega_pumpkin.png"),
        ("Luminosity", "Limited", "images/omega_luminosity_limited.png"),
        ("Luminosity", "Exotic", "images/omega_luminosity_exotic.png"),
        # ("", "", "images/omega_"),
    ],
    "Espio": [
        ("Default", "Legendary", "images/Espio_default.png"),
        ("Invisible", "Epic", "images/espio_invisible_epic.png"),
        ("Racesuit", "Exotic", "images/espio_racesuit_exotic.png"),
        ("Ninja", "Legendary", "images/espio_ninja_legendary.png"),
        ("Mummy", "Seasonal", "images/espio_mummy.png"),
        ("Luminosity", "Limited", "images/espio_luminosity_limited.png"),
        ("Luminosity", "Exotic", "images/espio_luminosity_exotic.png"),
        # ("", "", "images/espio_"),
    ],
    "Vector": [
        ("Default", "Legendary", "images/vector_default.png"),
        ("Riders", "Legendary", "images/vector_riders_legendary.png"),
        ("Gold Style", "Legendary", "images/vector_goldstyle_legendary.png"),
        ("Racesuit", "Exotic", "images/vector_racesuit_exotic.png"),
        ("Captain", "Exotic", "images/vector_captain_exotic.png"),
        ("DJ", "Exotic", "images/vector_dj_exotic.png"),
        ("Luminosity", "Exotic", "images/vector_luminosity_exotic.png"),
        ("Luminosity", "Limited", "images/vector_luminosity_limited.png"),
        # ("", "", "images/vector_"),
    ],
    "Charmy": [
        ("Default", "Legendary", "images/charmy_default.png"),
        ("Luminosity", "Limited", "images/charmy_luminosity_limited.png"),
        # ("", "", "images/charmy_"),
    ],
    "Blaze": [
        ("Default", "Legendary", "images/blaze_default.png"),
        ("Luminosity", "Limited", "images/blaze_luminosity_limited.png"),
        ("Luminosity", "Exotic", "images/blaze_luminosity_exotic.png"),
        ("Luminosity", "Exotic", "images/blaze_luminosity_exotic.png"),
        ("Maid", "Legendary", "images/blaze_maid_legendary.png"),
        ("Racesuit", "Legendary", "images/blaze_racesuit_legendary.png"),
        ("Rockstar", "Exotic", "images/blaze_rockstar_exotic.png"),
        ("Holiday Cheer", "Seasonal", "images/blaze_holiday.png"),
        ("Magical Girl", "Seasonal", "images/blaze_magicalgirl.png"),
        ("Summer", "Seasonal", "images/blaze_summer.png"),
        # ("", "", "images/blaze_"),
    ],
    "Silver": [
        ("Default", "Legendary", "images/silver_default.png"),
        ("Luminosity", "Limited", "images/silver_luminosity_limited.png"),
        ("Luminosity", "Exotic", "images/silver_luminosity_exotic.png"),
        ("Gold Style", "Legendary", "images/silver_goldstyle_legendary.png"),
        ("Racesuit", "Legendary", "images/silver_racesuit_legendary.png"),
        ("Riders", "Legendary", "images/silver_riders.png"),
        ("Rockstar", "Exotic", "images/silver_rockstar_exotic.png"),
        ("Steampunk", "Exotic", "images/silver_steampunk_exotic.png"),
        ("Holiday Cheer", "Seasonal", "images/silver_holiday.png"),
        ("Summer", "Seasonal", "images/silver_summer.png"),
        ("Vampire", "Seasonal", "images/silver_vampire.png"),
        ("Chrome Style", "Limited", "images/silver_chromestyle_limited.png"),
        # ("", "", "images/silver_.png"),
    ],
    "Marine": [
        ("Default", "Legendary", "images/marine_default.png"),
        # ("", "", "images/marine_"),
    ],
    "Jet": [
        ("Default", "Legendary", "images/jet_default.png"),
        ("Luminosity", "Limited", "images/jet_luminosity_limited.png"),
        ("Racesuit", "Legendary", "images/jet_racesuit_legendary.png"),
        ("Gold Style", "Exotic", "images/jet_goldstyle_exotic.png"),
        ("Winter", "Seasonal", "images/jet_winter.png"),
        ("Gold Style", "Limited", "images/jet_goldstyle_limited.png"),
        # ("", "", "images/jet_.png"),
    ],
    "Wave": [
        ("Default", "Legendary", "images/wave_default.png"),
        ("Summer", "Seasonal", "images/wave_summer.png"),
        # ("", "", "images/wave_"),
    ],
    "Storm": [
        ("Default", "Legendary", "images/storm_default.png"),
        ("Summer", "Seasonal", "images/storm_summer.png"),
        # ("", "", "images/storm_"),
    ],
    "Tangle": [
        ("Default", "Legendary", "images/tangle_default.png"),
        ("Summer", "Seasonal", "images/tangle_summer.png"),
        # ("", "", "images/tangle_"),
    ],
    "Whisper": [
        ("Default", "Exotic", "images/whisper_default.png"),
        ("Summer", "Seasonal", "images/whisper_summer.png"),
        # ("", "", "images/whisper_"),
    ],
    "Metal Sonic": [
        ("Default", "Legendary", "images/metal_default.png"),
        ("Luminosity", "Limited", "images/metal_luminosity_limited.png"),
        ("Luminosity", "Exotic", "images/metal_luminosity_exotic.png"),
        ("Chrome", "Epic", "images/metal_chrome_epic.png"),
        ("Hologram", "Legendary", "images/metal_hologram_legendary.png"),
        ("Armored", "Legendary", "images/metal_armored_legendary.png"),
        ("Holographic", "Exotic", "images/metal_holographic_exotic.png"),
        ("Racesuit", "Exotic", "images/metal_racesuit_exotic.png"),
        ("Circuit", "Exotic", "images/metal_circuit_exotic.png"),
        ("Gold", "Exotic", "images/metal_gold_exotic.png"),
        ("Heavy Metal", "Exotic", "images/metal_heavymetal_exotic.png"),
        ("Reaper", "Seasonal", "images/metal_reaper.png"),
        ("Grim Reaper", "Seasonal", "images/metal_grimreaper.png"),
        ("Gold", "Limited", "images/metal_gold_limited.png"),
        # ("", "", "images/metal_.png"),
    ],
    "Gemerl": [
        ("Default", "Exotic", "images/gemerl_default.png"),
        ("Scarecrow", "Legendary", "images/gemerl_scarecrow.png"),
        # ("", "", "images/gemerl_"),
    ],
    "Egg Robo": [
        ("Default", "Legendary", "images/eggrobo_default.png"),
        ("Missile", "Exotic", "images/eggrobo_missile.png"),
        # ("", "", "images/eggrobo_"),
    ],
    "E-10000": [
        ("E-10000G", "Legendary", "images/e10000g.png"),
        ("E-10000P", "Rare", "images/e10000p.png"),
        ("E-10000A", "Epic", "images/e10000a.png"),
        ("E-10000Y", "Legendary", "images/e10000y.png"),
        ("E-10000R", "Exotic", "images/e10000r.png"),
        # ("", "", "images/e10000"),
    ],
    "Classic Sonic": [
        ("Default", "Legendary", "images/classicsonic_default.png"),
        ("Tuxedo", "Legendary", "images/classicsonic_tuxedo_legendary.png"),
        ("Racesuit", "Legendary", "images/classicsonic_racesuit_legendary.png"),
        ("Holiday", "Seasonal", "images/classicsonic_holiday.png"),
        ("Pixel", "Legendary", "images/classicsonic_pixel_legendary.png"),
        ("Birthday", "Legendary", "images/classicsonic_birthday_legendary.png"),
        # ("", "", "images/classicsonic_"),
    ],
    "Classic Tails": [
        ("Default", "Legendary", "images/classictails_default.png"),
        ("Racesuit", "Legendary", "images/classictails_racesuit_legendary.png"),
        ("Pixel", "Exotic", "images/classictails_pixel_exotic.png"),
        # ("", "", "images/classictails_"),
    ],
    "Classic Knuckles": [
        ("Default", "Legendary", "images/classicknuckles_default.png"),
        ("Racesuit", "Legendary", "images/classicknuckles_racesuit_legendary.png"),
        ("Pixel", "Legendary", "images/classicknuckles_pixel_legendary.png"),
        # ("", "", "images/classicknuckles_"),
    ],
    "Classic Amy": [
        ("Default", "Legendary", "images/classicamy_default.png"),
        ("Racesuit", "Legendary", "images/classicamy_racesuit_legendary.png"),
        ("Pixel", "Legendary", "images/classicamy_pixel_legendary.png"),
        # ("", "", "images/classicamy_"),
    ],
}
